services:
  app:
    build:
      context: ../..
      dockerfile: docker/shipfree_dev/Dockerfile
    ports:
      - "3070:3000"
    environment:
      - NODE_ENV=development
      - HUSKY=0
    volumes:
      - ../../:/app
      - /app/node_modules
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9070:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data:
