services:
  app:
    build:
      context: ../..
      dockerfile: docker/shipfree_dev/Dockerfile
    ports:
      - "3070:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://devuser:devpass@postgres:5432/shipfreedev
      - NEXT_PUBLIC_DIRECTUS_URL=http://localhost:8070
      - DIRECTUS_INTERNAL_URL=http://directus_shipfree:8055

      - HUSKY=0
    volumes:
      - ../../:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.6-alpine
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=shipfreedev
      - POSTGRES_USER_DB_CREATE_PRIVILEGE=true
    ports:
      - "5470:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d shipfreedev"]
      interval: 5s
      timeout: 5s
      retries: 5

    # OPTIONAL
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5070:80"
    depends_on:
      - postgres

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_shipfree
    ports:
      - "9070:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  portainer_data:
