#!/bin/bash
set -e

# Grant full superuser privileges to user and create directus_db
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    ALTER USER ${DIRECTUS_DB_USER} WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS;
    CREATE DATABASE ${DIRECTUS_DB_DATABASE} OWNER ${DIRECTUS_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DIRECTUS_DB_DATABASE} TO ${DIRECTUS_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${DIRECTUS_DB_USER};
EOSQL

# Grant permissions on all tables in directus_db (for future tables)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${DIRECTUS_DB_DATABASE}" <<-EOSQL
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DIRECTUS_DB_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DIRECTUS_DB_USER};
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${DIRECTUS_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DIRECTUS_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DIRECTUS_DB_USER};
EOSQL
